apiVersion: v1
kind: Pod
metadata:
  name: pod-with-android-device
spec:
  restartPolicy: OnFailure
  containers:
    - image: alpine
      name: container-with-android-device
      command: ["sleep"]
      args: ["100000"]
      resources:
        limits:
          android/device: 1