apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: android-device-plugin-daemonset
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: android-device-plugin-ds
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - image: dimorinny/android-devices-kubernetes-plugin
          name: android-device-plugin-ctr
          imagePullPolicy: Never # TODO: delete
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: usb-devices
              mountPath: /dev/bus/usb/
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: usb-devices
          hostPath:
            path: /dev/bus/usb/